x-common-config: &common-config
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./nanobot/skills:/root/.claude/skills
    - ~/.nanobot/config.json:/root/.nanobot/config.json:ro
    - ~/git/teddy_ma_bot:/root/.nanobot/workspace
    - ./skills:/root/.nanobot/workspace/skills
    - ~/.gitconfig:/root/.gitconfig
    - ~/.ssh:/root/.ssh
    - /var/run/docker.sock:/var/run/docker.sock
  env_file:
    - .env

services:
  nanobot-gateway:
    container_name: nanobot-gateway
    <<: *common-config
    command: ["gateway"]
    restart: always
    ports:
      - 18790:18790

  nanobot-cli:
    <<: *common-config
    profiles:
      - cli
    command: ["status"]
    stdin_open: true
    tty: true
